spring:
  application:
    name: demo
  datasource:
     url: ${SPRING_DATASOURCE_URL}
     username: ${SPRING_DATASOURCE_USERNAME}
     password:  ${SPRING_DATASOURCE_PASSWORD}
     driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      encoding: UTF-8

# Swagger/OpenAPI configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8080


bank:
  bin: "970422"
  account:
    number: "0376929681"
    name: "Pham Thanh Phong"
  template: "compact"

sepay:
  api:
    url: "https://my.sepay.vn/userapi"
    token: "DL4YP5V0XTEITVEBYLNPU4G1DRQ28KF3WKUTM6RHCQ9EL5FN76BTJJWFUEL83QPR"
  polling:
    timeout: 900000

payment:
  polling:
    interval: 3000
  verification:
    maxRetries: 5



